spring:
  application:
    name: artinus

  datasource:
    url: ${DB_HOST}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

external:
  csrng:
    url: https://csrng.net
  gemini:
    api-key: ${GEMINI_API_KEY}

encryption:
  secret-key: ${ENCRYPTION_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
